@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNiwiZXhwIjoxNjUxNzg3NzExfQ.dfuRqp63jOpzAsI6CrUmeSVC8RIA5uurx4nhvPNdLx0


############  POSTS Requests  #################

#posts index
###
GET http://localhost:3000/posts

#post show
###
GET http://localhost:3000/posts/1

###
GET http://localhost:3000/current
Authorization: Bearer {{jwt}}
Content-Type: application/json



#post create
###
POST http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNiwiZXhwIjoxNjUxNzg3NzExfQ.dfuRqp63jOpzAsI6CrUmeSVC8RIA5uurx4nhvPNdLx0
Content-Type: application/json

{
  "user_id": 1,
  "title": "blueay!",
  "runs_taken": 41,
  "snow": "33",
  "weather": "basdfies",
  "description": "great fsshe sun",
  "resort": "snoqualmie",
  "photo": "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.2qiuosQijDiSp8amva23FwAAAA%26pid%3DApi&f=1"
}

#Post Delete
###
DELETE http://localhost:3000/posts/8

###
GET http://localhost:3000/users/13/posts 
Content-Type: application/json

{
  "user_id": 13
}

###
PATCH http://localhost:3000/users/22
Content-Type: application/json

{
  "name": "teeter"
}


################# USERS Requests ########################
#user index
###
GET http://localhost:3000/users



#user create
###
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "test",
  "email": "test@email.com",
  "password": "password",
  "password_confirmation": "password"
}

#user show
###
GET http://localhost:3000/users/1

###
GET http://localhost:3000/userposts/1

# ###
# GET https://api.weather.gov/gridpoints/SEW/151,53/forecast
# # periods = days
# # period 1 = day 1 ... 
# #period[0][:detailedForecast] should return todays detailed forecast
#three day
###
GET http://localhost:3000/threeDay
Content-Type: application/json

{
  "resort": "baker"
}

#lat and long gets snow in inches"
###
GET http://localhost:3000/forecast?resort=snowbird
Content-Type: application/json

{
  "resort": "snowbird"
}

# sessions create
###
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "boobs@email",
  "password": "password"
}







