Post.create!([
  {user_id: 3, title: "bob new post", runs_taken: 99, snow: "5in", weather: "The snow forecast for Mount Baker is: A light covering of new snow, mostly falling on Sat morning will be washed away by heavy rain (total 0.8in) on Sun afternoon. Freeze-thaw conditions (max 39°F on Sat night, min 21°F on Fri morning). Wind will be generally light.", description: "bob new desrioptioh", resort: "baker", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652461715/pag4lqk3dufiny1emmav.jpg", awards: nil, image_data: nil},
  {user_id: 18, title: "Stormy Day", runs_taken: 9, snow: "1in", weather: "The snow forecast for Niseko Annupuri is: Light rain (total 0.3in), mostly falling on Sat morning. Freeze-thaw conditions (max 54°F on Sat morning, min 32°F on Sat afternoon). Winds decreasing (near gales from the SW on Sat morning, light winds from the WSW by Sun morning).", description: "Winter pow storm!", resort: "niseko", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652472965/m1v4yvcy0axzx12kemlv.jpg", awards: nil, image_data: nil},
  {user_id: 2, title: "Stormy powder day!", runs_taken: 19, snow: "5in", weather: "The snow forecast for Mount Baker is: A light covering of new snow, mostly falling on Sat morning will be washed away by heavy rain (total 1.0in) on Sun afternoon. Freeze-thaw conditions (max 41°F on Sun night, min 23°F on Fri morning). Wind will be generally light.", description: "great day up a baker riding some nice light powder", resort: "baker", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652475270/ltgi9osydixmryxktq8h.jpg", awards: nil, image_data: nil},
  {user_id: 2, title: "decent day today", runs_taken: 6, snow: "4in", weather: "The snow forecast for Palisades Tahoe is: Mostly dry. Very mild (max 52°F on Sat afternoon, min 36°F on Fri morning). Winds increasing (light winds from the SSW on Sat night, fresh winds from the WSW by Sun night).", description: "Some flat light, little snow, but fun times", resort: "squaw", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652476976/k6didvjzinwcwcugv7bg.jpg", awards: nil, image_data: nil},
  {user_id: 2, title: "powder!", runs_taken: 33, snow: "1in", weather: "The snow forecast for Niseko Annupuri is: Light rain (total 0.1in), mostly falling on Sun morning. Freeze-thaw conditions (max 46°F on Tue morning, min 30°F on Sat night). Winds decreasing (strong winds from the W on Sun night, moderate winds from the SW by Tue morning).", description: "nice deep powder day!", resort: "niseko", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652554243/bsh5n64s4qkezl5cvhwh.jpg", awards: nil, image_data: nil},
  {user_id: 1, title: "Powder!!!", runs_taken: 99, snow: "9in", weather: "The snow forecast for Mount Baker is: Light rain (total 0.1in) on Mon morning. Becoming colder with heavy fall of snow, heaviest during Wed morning. Freeze-thaw conditions (max 37°F on Tue afternoon, min 23°F on Wed night). Wind will be generally light.", description: "pow day with some great friends!", resort: "baker", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652716291/gjszsatf4judwvjocw5b.jpg", awards: nil, image_data: nil},
  {user_id: 12, title: "Storm Boarding", runs_taken: 9, snow: "6in", weather: "The snow forecast for Crystal Mountain is: A moderate fall of snow, heaviest on Wed morning. Freeze-thaw conditions (max 36°F on Tue afternoon, min 18°F on Wed night). Winds increasing (light winds from the WSW on Mon morning, fresh winds from the W by Wed afternoon).", description: "a stormy blizzard day today!", resort: "crystal", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652720624/s7o7yjdvfoaau4aklzkw.jpg", awards: nil, image_data: nil},
  {user_id: 1, title: "DEEEEEP powder day!", runs_taken: 9, snow: "5in", weather: "The snow forecast for Sierra Nevada is: Mostly dry. Mild temperatures (max 43°F on Sat afternoon, min 36°F on Fri afternoon). Winds increasing (calm on Fri afternoon, near gales from the SW by Sat night).", description: "had a blast riding the deep pow at sierra", resort: "sierra", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652466330/ko3z42eeizxmp075kid2.jpg", awards: nil, image_data: nil},
  {user_id: 20, title: "Super sick day!", runs_taken: 95, snow: "7in", weather: "The snow forecast for Stevens Pass is: A heavy fall of snow, heaviest during Wed night. Freeze-thaw conditions (max 37°F on Tue afternoon, min 21°F on Wed night). Mainly fresh winds.", description: "Fun time ripping thru the trees and down groomers!", resort: "stevens", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652732629/vneeswmj5ziaq3kxrtmv.jpg", awards: nil, image_data: nil},
  {user_id: 20, title: "Long lines today...", runs_taken: 1, snow: "2in", weather: "The snow forecast for Mammoth Mountain is: Mostly dry. Very mild (max 52°F on Wed afternoon, min 37°F on Mon night). Wind will be generally light.", description: "Too many people!", resort: "mammoth", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652732799/j8gmrdajydplg9fvfehk.jpg", awards: nil, image_data: nil},
  {user_id: 21, title: "Great day hitting the pipe!", runs_taken: 81, snow: "2in", weather: "The snow forecast for Mammoth Mountain is: Mostly dry. Very mild (max 52°F on Wed afternoon, min 37°F on Mon night). Wind will be generally light.", description: "fun and sunny park day!", resort: "mammoth", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652733268/ey9xfs4vyakirflkyqlb.png", awards: nil, image_data: nil},
  {user_id: 23, title: "perfect night boarding!", runs_taken: 9, snow: "3in", weather: "The snow forecast for Summit at Snoqualmie is: Mild at first with light rain (total 0.2in) on Mon afternoon followed by colder weather and light fall of snow, heaviest on Wed night. Freeze-thaw conditions (max 41°F on Tue afternoon, min 27°F on Wed night). Wind will be generally light.", description: "got the inside scoop on some weather!", resort: "snoqualmie", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652733529/d2dvd5tzowv5ucq6b6ho.jpg", awards: nil, image_data: nil},
  {user_id: 4, title: "Riding with Friends!", runs_taken: 6, snow: "1in", weather: "The snow forecast for Taos is: Mostly dry. Very mild (max 52°F on Mon afternoon, min 43°F on Mon night). Winds decreasing (near gales from the SW on Mon afternoon, light winds from the WSW by Wed morning).", description: "fun day sliding around with my pals!", resort: "taos", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652734540/edsmlhibcr6zv6ygcat6.jpg", awards: nil, image_data: nil},
  {user_id: 4, title: "Fun spring day!", runs_taken: 9, snow: "4in", weather: "The snow forecast for Heavenly is: Mostly dry. Very mild (max 52°F on Wed afternoon, min 34°F on Thu night). Winds increasing (calm on Tue morning, strong winds from the W by Thu afternoon).", description: "had fun taking some spring laps and enjoying friends, sun, and some beers!", resort: "heavenly", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652815769/mzuzog7dxqg60ax0ei1z.jpg", awards: nil, image_data: nil},
  {user_id: 2, title: "Not so fun today..", runs_taken: 5, snow: "3in", weather: "The snow forecast for Summit at Snoqualmie is: A light fall of snow, heaviest on Wed morning. Turning milder with light rain (total 0.2in) on Wed morning. Freeze-thaw conditions (max 41°F on Tue afternoon, min 28°F on Wed night). Winds increasing (calm on Tue night, strong winds from the WSW by Wed afternoon).", description: "Long lines, no snow", resort: "snoqualmie", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652836612/jevo1xdkplwsluhqi2jz.jpg", awards: nil, image_data: nil},
  {user_id: 3, title: "calming day in japan", runs_taken: 17, snow: "1in", weather: "The snow forecast for Mt Moiwa ski area is: Light rain (total 0.2in), mostly falling on Thu afternoon. Very mild (max 66°F on Sat morning, min 50°F on Wed night). Wind will be generally light.", description: "Nice sunny day here in moiwa", resort: "moiwa", photo: "https://res.cloudinary.com/dyo12/image/upload/v1652896965/fpghwy6tlrnuly2lrzvk.jpg", awards: nil, image_data: nil}
])
User.create!([
  {name: "derek", email: "derek@email.com", password_digest: "$2a$12$njanXD8BYsh7QY03a/5jIeeK8/y9qpMq54E5uF.6dFOWtVaOaIi5y", profile_picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.Trf3m9vSt0E2w0lTvDbIPQHaHa%26pid%3DApi&f=1"},
  {name: "bob", email: "bob@email.com", password_digest: "$2a$12$yxTKnPuw.WdrSFBEFWNrrunz/4Wy8kNYJejarsODX7SZg/chYCTCS", profile_picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.JtFR1mW09DzJ9-oifV7PfAHaLh%26pid%3DApi&f=1"},
  {name: "jimi", email: "jimi@email.com", password_digest: "$2a$12$8xXMv3Of0EbKSOoTZV93MeVfp5uKaMx6m.ECs./0SiOFy7CRyDPri", profile_picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.8DLSwdZ5edkBu9rgk7MNkAHaGL%26pid%3DApi&f=1"},
  {name: "john lennon", email: "john@email.com", password_digest: "$2a$12$cz2pCk3n.z93Cx967okT6.i30OjmcEBcJsX39vfLtlSghk0pSSxxi", profile_picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.-0jTWcm6WuwwPCu2qknPOQHaFj%26pid%3DApi&f=1"},
  {name: "Micheal Jackson", email: "micheal@email.com", password_digest: "$2a$12$DYRJJBc39gR3hZSy6segKuOaxRheY9ej4XkRc9sgJBZih4kDarq/W", profile_picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.6-CfEs1jeg9xY9GNze86KQHaJY%26pid%3DApi&f=1"},
  {name: "DAVID", email: "test@email.com", password_digest: "$2a$12$.2K2FubhZyWX67xfB9XRe.g3IafP4MMU08hhma/ou8NMAH8clEJ36", profile_picture: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.Db7FJNEpLjZsLkoYx1T5uAHaKn%26pid%3DApi&f=1"},
  {name: "bill", email: "bill@email.com", password_digest: "$2a$12$CgLWOdoKKuIleCg0gE9u2.qupb3BMvWAIXCU1yKKNI05rVuYI7jFG", profile_picture: "https://res.cloudinary.com/dyo12/image/upload/v1652732541/esevqggrhjnyytxpitus.png"},
  {name: "lindsey", email: "lindsey@email.com", password_digest: "$2a$12$2MPYh.tL5xWnENTdY2uMNeSB27VdaABB2FdxGyLD05iPyMGT0zpgy", profile_picture: "https://res.cloudinary.com/dyo12/image/upload/v1652732845/ebrxt4anhrwle731rbji.png"},
  {name: "robert", email: "robert@email.com", password_digest: "$2a$12$A0UTX4eVQ8tELhbnQOBoRuqWcN1rU9wevs5h.D1o1BpXG4w3bXUMi", profile_picture: "https://res.cloudinary.com/dyo12/image/upload/v1652733073/j56jllrpyoofbbxmwmsq.png"},
  {name: "martha", email: "martha@email.com", password_digest: "$2a$12$1p5Ep/RNPZm6asJRPD0oKe2YEwCiSfEHlHteqKYPPUuvue6hbiMHC", profile_picture: "https://res.cloudinary.com/dyo12/image/upload/v1652733383/tqo79ezhbkcllvejqc5m.png"},
  {name: "matt cole", email: "matt@email.com", password_digest: "$2a$12$cEouRkCkc9XJ2JSGSbUXjeqq4n9WlB6l505ZMyOGvAlPXwDV6iL8C", profile_picture: "https://res.cloudinary.com/dyo12/image/upload/v1652472772/yfqboip9jaas1qi4spzd.jpg"},
  {name: "derk", email: "derk@email.com", password_digest: "$2a$12$CJaDuIB39xZJNz.HPJ.OCOivDQ3dIkIEUgWYc9hdyJqgZr/RfwKi.", profile_picture: "https://res.cloudinary.com/dyo12/image/upload/v1652472896/znm34mmnhuuqoenhjx81.jpg"},
  {name: "vanessa", email: "v@email.com", password_digest: "$2a$12$zo6yCPPSfJU05rkZ7UCLxOkaXgYNDI1Wd2oUcFiHo0p2fk4n58DZK", profile_picture: "https://res.cloudinary.com/dyo12/image/upload/v1652486034/lzmroen1b0sm4ojaoneq.jpg"}
])
